- hosts: allhosts
  tasks:
     - name: "shut down CentOS 6 and Debian 7 systems"
       command: /sbin/shutdown -t now
       when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6") or
             (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "7")