- hosts: allhosts
  vars:
    file_name: test
  tasks:
    - name: copy file
      copy: src=touch /tmp/{{file_name}} dest=/tmp
      chmod: 0644 
      stat:
        path: "/tmp/{{file_name}}" 
        register: file
    - debug:
        var: file
        msg: "the file exists"
      when: file.stat.exists == true        