- hosts: allhosts
  vars:
    file_name: test
  tasks:
    - name: create file
      shell: touch /tmp/{{file_name}} 
    - name: retrieve the data of the {{file_name}} 
      stat:
        path: "/tmp/{{file_name}} 
        register: file
    - debug:
        var: file
        msg: "the file exists"
      when: file.stat.exists == true        