- hosts: all-hosts
    remote_user: ansadmin
    become: yes
   tasks:
      - name: install httpd package
        yum: name=httpd state=installed
      - name: create index.html
        copy: src=index.html dest=/var/www/html    
        
